AllCops:
  TargetRubyVersion: 2.4
  AutoCorrect: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/TrailingEmptyLines:
   Enabled: false
   
 Metrics/MethodLength:
   Enabled: false
