name: Run

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.90.0
        with:
          ruby-version: 3.1
          bundler: latest
      - run: |
          ${{ github.event.inputs.command }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
